### ISSUE TITLE
Schedule Time to View FPGA Boards

### ISSUE THREAD

**Issue by starksbe** [starksbe/ISU-ECE-5508-S23#7]

**Comment by persjere** [comment]
My schedule is typically open during the following timeslots. I would also be fine meeting up in person during the normally scheduled class time.

Mon: 11 am - 11:45 am, After 3:15 pm
Tues: After 3:15 pm
Wed: 11 am - 11:45 am, After 3:15 pm
Thurs: After 3:15 pm
Friday: 8 am to 5 pm

**Comment by starksbe** [comment]
I think since we were able to grab the boards, there is no need to meet in person to view the boards since having them is a much better substitute. If we can get a response from everyone on this thread, I'll mark this issue as done. Otherwise, I'll bring this issue up in class and we can mark it done there.

I'll be creating a new issue to formally select a time for us to meet together to discuss details and progress of the project so having availabilities in this thread will be helpful.

I am available to meet virtually through zoom any time after 16:00 on Mon, Tues, Thurs, Fri, Sat or in person later on these weekdays.

**Comment by nataliacastaneda** [comment]
Sounds good, just wanted to report that I have picked up my board.
