### ISSUE TITLE
Setup Zoom Meeting for Planning & Progress Reporting

### ISSUE THREAD

**Issue by starksbe** [starksbe/ISU-ECE-5508-S23#8]

**Comment by starksbe** [comment]
We need to find a time at least once per week that we can meet for fifteen to thirty minutes for planning and progress reporting. The goal is to break up the project into smaller tasks that we can accomplish each week to two weeks, not to pressure each other to work faster. If done right, the team should be able to tackle smaller issues in a convenient, non-invasive fashion.

**Comment by persjere** [comment]
For most weeks, my schedule is open between 11 am and 11:45 pm on Monday/Wednesday, after 3:15 pm Monday through Thursday, or between 8 am and 5 pm on Friday.

**Comment by nataliacastaneda** [comment]
Every weekday besides Tuesday I can be available between 2 pm and 5 pm.

**Comment by Roomybear** [comment]
I'm available all day Fridays and on the weekends.
